"""empty message

Revision ID: 0f3b81db9357
Revises: d47aec8a014a
Create Date: 2022-06-03 08:58:25.925227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3b81db9357'
down_revision = 'd47aec8a014a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_description')
    # ### end Alembic commands ###
